# Generated by Django 4.0.3 on 2022-04-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.doctortimeslot')),
            ],
        ),
    ]
